### ISSUE TITLE
SlidingRender behavior!!!

### ISSUE THREAD

**Issue by MeoMix** [MarionetteLabs/marionette-cookbook#24]
http://codepen.io/MeoMix/pen/sfjiL

I might go through and spruce it up with a few more comments if anything is really unclear. Feel free to clean it up more.

I refactored it today so that _getMaxRenderIndex returns an inclusive result (as opposed to exclusive) so that it is consistent with _getMinRenderIndex. Additionally, I introduced a threshold parameter (defaults to 10) which will load 10 items before/after outside of the viewport. This is adjustable and is used to combat load-flickering.

The example provided renders 10,000 elements. You can scroll up/down or drag it as much as you'd please and it will keep up. 10 items before/after outside of the viewport are rendered as well as everything inside of it. The scrollbar doesn't jump, too!!

:+1:

**Comment by joshbedo** [comment]
We can probably close this issue since it's related to [#35](https://github.com/MarionetteLabs/marionette-cookbook/pull/35)
